#! /bin/bash

start_mpvpaper() {
	mpvpaper -o "--hwdec=nvdec --gpu-api=vulkan --loop-file=inf --no-audio" ALL ~/Insync/luctreis@gmail.com/OneDrive/wallpapers/sala.mp4
}

kill_mpvpaper() {
    killall mpvpaper
}

while true; do
    start_mpvpaper
    sleep 1800
    kill_mpvpaper
    sleep 1
done
