#! /bin/bash

MONITOR=$(hyprctl activewindow | sed -nE 's/.*at: (-?[0-9]+),(-?[0-9]+)/\1/p')

CURRENT=$(hyprctl activewindow | sed -nE 's/.*floating: ([01])/\1/p')

if [ "$CURRENT" == "0" ]; then
	hyprctl dispatch setfloating active
	hyprctl dispatch resizeactive exact 1876 1003
	hyprctl dispatch moveactive exact 22 55
elif [ "$CURRENT" == "1" ]; then
	hyprctl dispatch settiled active
fi
